# Generated by Django 4.0.6 on 2022-11-12 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('branch', models.CharField(max_length=50)),
                ('year_joined', models.DateField()),
                ('year_passed', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('connections', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
