# Generated by Django 4.0.6 on 2022-11-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='connections',
        ),
    ]
