# Generated by Django 4.0.3 on 2022-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_custom_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='user',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='connections',
            field=models.ManyToManyField(to='home.user'),
        ),
    ]
