# Generated by Django 4.0.6 on 2022-11-26 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('branch', models.CharField(max_length=50)),
                ('year_joined', models.DateField()),
                ('year_passed', models.DateField(default=True)),
                ('password', models.CharField(max_length=50)),
                ('connections', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('company', models.CharField(max_length=100, null=True)),
                ('working_experience', models.IntegerField()),
                ('SDE', models.BooleanField(default=False)),
                ('ML_DL', models.BooleanField(default=False)),
                ('DS', models.BooleanField(default=False)),
                ('Management', models.BooleanField(default=False)),
                ('Others', models.BooleanField(default=False)),
            ],
        ),
    ]
