# Generated by Django 4.0.6 on 2022-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='isAlumni',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
