# Generated by Django 4.0.6 on 2022-11-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_custom_user_isalumni_custom_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='DS',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='ML_DL',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='Management',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='Others',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='SDE',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='isAlumni',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='working_experience',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='year_joined',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='year_passed',
        ),
    ]
